[package]
name = "login"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.34"
jsonwebtoken = "9.2.0"
serde = { version = "1.0.197", features = ["derive"] }
actix-web = "4.5.1"
serde_json = "1.0.114"